package com.mycompany.projeto.Register;


import java.sql.*;
import javax.swing.*;
import com.mycompany.projeto.Login.Login;
import com.mycompany.projeto.JDBC.MySQL;

public class Register extends javax.swing.JFrame {

    Connection connection = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form login
     */
    public Register() {
        initComponents();
        connection = MySQL.conector();
        System.out.println(connection);
    }

    //Método para Adcionar Usuários
    private void adicionar() {

        String sql = "insert into tblUsuario(nome,email,senha,perfil) values(?,?,?,?)";
        try {
            pst = connection.prepareStatement(sql);

            pst.setString(1, txtUsernameRegister.getText());
            pst.setString(2, txtEmailRegister.getText());
            //Modo mais seguro de capturar a senha
            String captura = new String(txtPasswordRegister.getPassword());
            pst.setString(3, captura);
            pst.setString(4, cboTipoUser.getSelectedItem().toString());

            //Validação dos campos obrigatórios
            if ((txtEmailRegister.getText().isEmpty()) || (captura.isEmpty()) || (txtUsernameRegister.getText().isEmpty())) {
                JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");

            } else {
                //Linha a baixo atualiza a tabela Usuario com os dados do formulário
                int adicionado = pst.executeUpdate();
                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");

                    txtEmailRegister.setText(null);
                    txtPasswordRegister.setText(null);
                    txtUsernameRegister.setText(null);
                }
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCreateBy = new javax.swing.JLabel();
        lblBackgroundIcon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSubTitle = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmailRegister = new javax.swing.JTextField();
        lblUnderscore = new javax.swing.JLabel();
        lblUserIcon = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPasswordRegister = new javax.swing.JPasswordField();
        lblUnderscore2 = new javax.swing.JLabel();
        lblDisableIcon = new javax.swing.JLabel();
        lblShowIcon = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        lblFooter = new javax.swing.JLabel();
        lblUserIcon1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        txtUsernameRegister = new javax.swing.JTextField();
        lblUnderscore3 = new javax.swing.JLabel();
        lblUserIcon2 = new javax.swing.JLabel();
        lblReturnIcon = new javax.swing.JLabel();
        lblUsername1 = new javax.swing.JLabel();
        cboTipoUser = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreateBy.setFont(new java.awt.Font("Sitka Small", 1, 13)); // NOI18N
        lblCreateBy.setForeground(new java.awt.Color(25, 118, 211));
        lblCreateBy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateBy.setText("Seeds");
        jPanel1.add(lblCreateBy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 500, -1));

        lblBackgroundIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Richard\\Desktop\\images\\background.png")); // NOI18N
        jPanel1.add(lblBackgroundIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 500, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 440));

        jPanel2.setBackground(new java.awt.Color(25, 118, 211));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        jPanel2.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, 29));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Cadastro");
        jPanel2.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 420, 41));

        lblSubTitle.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblSubTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubTitle.setText("Olá! Vamos começar");
        jPanel2.add(lblSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 420, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(199, 226, 255));
        lblEmail.setText("Email *");
        jPanel2.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 341, -1));

        txtEmailRegister.setBackground(new java.awt.Color(25, 118, 211));
        txtEmailRegister.setFont(txtEmailRegister.getFont().deriveFont(txtEmailRegister.getFont().getSize()+2f));
        txtEmailRegister.setForeground(new java.awt.Color(255, 255, 255));
        txtEmailRegister.setBorder(null);
        txtEmailRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(txtEmailRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 240, 30));

        lblUnderscore.setForeground(new java.awt.Color(255, 255, 255));
        lblUnderscore.setText("_________________________________________");
        jPanel2.add(lblUnderscore, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 290, 39));

        lblUserIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Richard\\Desktop\\images\\usericon.png")); // NOI18N
        jPanel2.add(lblUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 40, 39));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(199, 226, 255));
        lblPassword.setText("Password *");
        jPanel2.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 341, -1));

        txtPasswordRegister.setBackground(new java.awt.Color(25, 118, 211));
        txtPasswordRegister.setFont(txtPasswordRegister.getFont().deriveFont(txtPasswordRegister.getFont().getSize()+2f));
        txtPasswordRegister.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordRegister.setBorder(null);
        txtPasswordRegister.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtPasswordRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 240, 30));

        lblUnderscore2.setForeground(new java.awt.Color(255, 255, 255));
        lblUnderscore2.setText("_________________________________________");
        jPanel2.add(lblUnderscore2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 290, 40));

        lblDisableIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDisableIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Richard\\Desktop\\images\\eyeclose.png")); // NOI18N
        lblDisableIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDisableIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDisableIconMouseClicked(evt);
            }
        });
        jPanel2.add(lblDisableIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 40, 40));

        lblShowIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShowIcon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Richard\\Desktop\\images\\eyeopen.png")); // NOI18N
        lblShowIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShowIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowIconMouseClicked(evt);
            }
        });
        jPanel2.add(lblShowIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 40, 40));

        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(25, 118, 211));
        btnRegister.setText("CADASTRAR");
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 140, 40));

        lblFooter.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblFooter.setForeground(new java.awt.Color(199, 226, 255));
        lblFooter.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFooter.setText("Seja Bem-Vindo(a)");
        jPanel2.add(lblFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 120, -1));

        lblUserIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblUserIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 147, 40, 39));

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(199, 226, 255));
        lblUsername.setText("Name *");
        jPanel2.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 341, -1));

        txtUsernameRegister.setBackground(new java.awt.Color(25, 118, 211));
        txtUsernameRegister.setFont(txtUsernameRegister.getFont().deriveFont(txtUsernameRegister.getFont().getSize()+2f));
        txtUsernameRegister.setForeground(new java.awt.Color(255, 255, 255));
        txtUsernameRegister.setBorder(null);
        txtUsernameRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsernameRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 240, 30));

        lblUnderscore3.setForeground(new java.awt.Color(255, 255, 255));
        lblUnderscore3.setText("_________________________________________");
        jPanel2.add(lblUnderscore3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 290, 39));

        lblUserIcon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserIcon2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Richard\\Desktop\\images\\usericon.png")); // NOI18N
        jPanel2.add(lblUserIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 40, 39));

        lblReturnIcon.setForeground(new java.awt.Color(255, 255, 255));
        lblReturnIcon.setText("Return to Login Page");
        lblReturnIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReturnIcon.setMaximumSize(new java.awt.Dimension(10, 10));
        lblReturnIcon.setMinimumSize(new java.awt.Dimension(10, 10));
        lblReturnIcon.setName(""); // NOI18N
        lblReturnIcon.setPreferredSize(new java.awt.Dimension(10, 10));
        lblReturnIcon.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        lblReturnIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReturnIconMouseClicked(evt);
            }
        });
        jPanel2.add(lblReturnIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 30));

        lblUsername1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblUsername1.setForeground(new java.awt.Color(199, 226, 255));
        lblUsername1.setText("Escolha uma opção de perfil:");
        jPanel2.add(lblUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 341, -1));

        cboTipoUser.setBackground(new java.awt.Color(25, 118, 211));
        cboTipoUser.setForeground(new java.awt.Color(255, 255, 255));
        cboTipoUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "doador", "donatario" }));
        cboTipoUser.setBorder(null);
        jPanel2.add(cboTipoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 80, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 420, 440));

        setSize(new java.awt.Dimension(916, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.1) {
            String val = i + "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void lblShowIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowIconMouseClicked
        txtPasswordRegister.setEchoChar((char) 8226);
        lblDisableIcon.setVisible(true);
        lblDisableIcon.setEnabled(true);
        lblShowIcon.setEnabled(false);
        lblShowIcon.setEnabled(false);
    }//GEN-LAST:event_lblShowIconMouseClicked

    private void lblDisableIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDisableIconMouseClicked
        txtPasswordRegister.setEchoChar((char) 0);
        lblDisableIcon.setVisible(false);
        lblDisableIcon.setEnabled(false);
        lblShowIcon.setEnabled(true);
        lblShowIcon.setEnabled(true);
    }//GEN-LAST:event_lblDisableIconMouseClicked

    private void txtEmailRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailRegisterActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // Chamando o método adicionar
        adicionar();
        Login login = new Login();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtUsernameRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameRegisterActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblReturnIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnIconMouseClicked
        // TODO add your handling code here:   Register register = new Register();
        Login login = new Login();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_lblReturnIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cboTipoUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBackgroundIcon;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblCreateBy;
    private javax.swing.JLabel lblDisableIcon;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblReturnIcon;
    private javax.swing.JLabel lblShowIcon;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUnderscore;
    private javax.swing.JLabel lblUnderscore2;
    private javax.swing.JLabel lblUnderscore3;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JLabel lblUserIcon1;
    private javax.swing.JLabel lblUserIcon2;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername1;
    private javax.swing.JTextField txtEmailRegister;
    private javax.swing.JPasswordField txtPasswordRegister;
    private javax.swing.JTextField txtUsernameRegister;
    // End of variables declaration//GEN-END:variables
}
